services:
  backend:
    build: ./backend
    image: mahmoudkhera/backend
    container_name: inventory-backend
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      - BACK_END_API=0.0.0.0
      - PORT=4000
      - DATABASE_URL=postgresql://neondb_owner:npg_hvPKynr4qZt9@ep-late-snow-ags00p3q-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=verify-full
    
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    image: mahmoudkhera/frontend
    container_name: inventory-frontend
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      # CHANGE THIS: Use localhost because your browser is the one making the request
      - API_URL=http://localhost:4000
    


