---
# Play 1 — Configure Nginx Proxy on Machine 
- name: Configure Nginx Proxy on Machine A
  hosts: nginx
  become: true
  tags: nginx
  vars_files:
    - vars/secrets.yml
    - roles/front/vars/main.yml
  roles:
     - role: nginx


# Play 2 — Configure front server 
- name: setup front 
  hosts: front
  become: true
  tags: front
  vars_files:
    - vars/secrets.yml
  roles:
     - role: front


# Play 2 — Configure front server 
- name: setup backend 
  hosts: backend
  become: true
  tags: backend
  vars_files:
    - vars/secrets.yml
  roles:
     - role: backend
