---
- name: Create app directory
  file:
    path: "/home/ubuntu/app"
    state: directory
- name: Copy .env file  
  copy:
    src: files/.env
    dest: /home/ubuntu/app/.env
    mode: '0600'
- name: Copy docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: "/home/ubuntu/app/docker-compose.yml"


- name: Run docker compose down
  command: docker compose down
  args:
    chdir: "/home/ubuntu/app"

- name: Run docker compose up
  command: docker compose up -d
  args:
    chdir: "/home/ubuntu/app"